package com.kotlinstudies.tabelaperiodicainterativa.datasource

import com.kotlinstudies.tabelaperiodicainterativa.R
import com.kotlinstudies.tabelaperiodicainterativa.models.ChemicalElementDetails

object Details {
   val hidrogenioDetails = ChemicalElementDetails(
      elementId = 0,
      R.drawable.hidrogenio,
      series = R.string.series_diatomic_nonmetal,
      period = 1,
      group = 1,
      yearDiscovered = "1766",
      standardState = R.string.standard_state_gas,
      description = R.string.hydrogen_desc,
      electronicConfiguration = "1s¹",
      atomicMass = "1.00794(4)",
      electronegativity = "2.2",
      atomicRadius = "37",
      ionizationEnergy = "1312.0",
      electronAffinity = "72.8",
      oxidationStates = "±1",
      density = "0.0000899",
      meltingPoint = "14.025",
      boilingPoint = "20.268"
   )

   val helioDetails = ChemicalElementDetails(
      elementId = 1,
      R.drawable.helio,
      series = R.string.series_noble_gas,
      period = 1,
      group = 18,
      yearDiscovered = "1868",
      standardState = R.string.standard_state_gas,
      description = R.string.helio_desc,
      electronicConfiguration = "1s²",
      atomicMass = "4.002602(2)",
      electronegativity = "0.0",
      atomicRadius = "32",
      ionizationEnergy = "2372.3",
      electronAffinity = "0.0",
      oxidationStates = "0",
      density = "0.1785",
      meltingPoint = "0.95",
      boilingPoint = "4.22"
   )

   val litioDetails = ChemicalElementDetails(
      elementId = 2,
      R.drawable.litio,
      series = R.string.series_alkali_metal,
      period = 2,
      group = 1,
      yearDiscovered = "1817",
      standardState = R.string.standard_state_solid,
      description = R.string.litio_desc,
      electronicConfiguration = "1s² 2s¹",
      atomicMass = "6.941(2)",
      electronegativity = "0.98",
      atomicRadius = "134",
      ionizationEnergy = "520.2",
      electronAffinity = "59.6",
      oxidationStates = "±1",
      density = "535.0",
      meltingPoint = "453.0",
      boilingPoint = "1615.0"
   )

   val berilioDetails = ChemicalElementDetails(
      elementId = 3,
      R.drawable.berilio,
      series = R.string.series_alkaline_earth_metal,
      period = 2,
      group = 2,
      yearDiscovered = "1797",
      standardState = R.string.standard_state_solid,
      description = R.string.berilio_desc,
      electronicConfiguration = "1s² 2s²",
      atomicMass = "9.012182(3)",
      electronegativity = "1.57",
      atomicRadius = "90",
      ionizationEnergy = "899.5",
      electronAffinity = "0.0",
      oxidationStates = "+2, +1",
      density = "1848.0",
      meltingPoint = "1560.0",
      boilingPoint = "2744.0"
   )

   val boroDetails = ChemicalElementDetails(
      elementId = 4,
      R.drawable.boro,
      series = R.string.series_semimetal,
      period = 2,
      group = 13,
      yearDiscovered = "1808",
      standardState = R.string.standard_state_solid,
      description = R.string.boro_desc,
      electronicConfiguration = "1s² 2s² 2p¹",
      atomicMass = "10.811(7)",
      electronegativity = "2.04",
      atomicRadius = "82",
      ionizationEnergy = "800.6",
      electronAffinity = "26.7",
      oxidationStates = "+4, +3, +2, +1",
      density = "2460.0",
      meltingPoint = "2348.0",
      boilingPoint = "4273.0"
   )

   val carbonoDetails = ChemicalElementDetails(
      elementId = 5,
      R.drawable.carbono,
      series = R.string.series_polyatomic_nonmetal,
      period = 2,
      group = 14,
      yearDiscovered = "1789",
      standardState = R.string.standard_state_solid,
      description = R.string.carbon_desc,
      electronicConfiguration = "[He] 2s² 2p²",
      atomicMass = "12.0107(8)",
      electronegativity = "2.55",
      atomicRadius = "77",
      ionizationEnergy = "1086.5",
      electronAffinity = "153.9",
      oxidationStates = "+4",
      density = "2267.0",
      meltingPoint = "3823.0",
      boilingPoint = "5100.15"
   )

   val nitrogenioDetails = ChemicalElementDetails(
      elementId = 6,
      R.drawable.nitrogenio,
      series = R.string.series_diatomic_nonmetal,
      period = 2,
      group = 15,
      yearDiscovered = "1772",
      standardState = R.string.standard_state_gas,
      description = R.string.nitrogen_desc,
      electronicConfiguration = "[He] 2s² 2p³",
      atomicMass = "14.0067(2)",
      electronegativity = "3.04",
      atomicRadius = "75",
      ionizationEnergy = "1402.3",
      electronAffinity = "0.0",
      oxidationStates = "+5, +4, ±3, +2",
      density = "1.2506",
      meltingPoint = "63.15",
      boilingPoint = "75.36"
   )

   val oxigenioDetails = ChemicalElementDetails(
      elementId = 7,
      R.drawable.oxigenio,
      series = R.string.series_diatomic_nonmetal,
      period = 2,
      group = 16,
      yearDiscovered = "1774",
      standardState = R.string.standard_state_gas,
      description = R.string.oxygen_desc,
      electronicConfiguration = "[He] 2s² 2p⁴",
      atomicMass = "15.9994(3)",
      electronegativity = "3.44",
      atomicRadius = "73",
      ionizationEnergy = "1313.9",
      electronAffinity = "141.0",
      oxidationStates = "-2, -1",
      density = "1.429",
      meltingPoint = "50.35",
      boilingPoint = "90.18"
   )

   val fluorDetails = ChemicalElementDetails(
      elementId = 8,
      R.drawable.fluor,
      series = R.string.series_diatomic_nonmetal,
      period = 2,
      group = 17,
      yearDiscovered = "1529",
      standardState = R.string.standard_state_gas,
      description = R.string.fluor_desc,
      electronicConfiguration = "[He] 2s² 2p⁵",
      atomicMass = "18.9984032(5)",
      electronegativity = "3.98",
      atomicRadius = "71",
      ionizationEnergy = "1681.0",
      electronAffinity = "328.0",
      oxidationStates = "-1",
      density = "1.696",
      meltingPoint = "53.53",
      boilingPoint = "85.03"
   )

   val neonioDetails = ChemicalElementDetails(
      elementId = 9,
      R.drawable.neonio,
      series = R.string.series_noble_gas,
      period = 2,
      group = 18,
      yearDiscovered = "1898",
      standardState = R.string.standard_state_gas,
      description = R.string.neonio_desc,
      electronicConfiguration = "[He] 2s² 2p⁶",
      atomicMass = "20.1797(6)",
      electronegativity = "0.0",
      atomicRadius = "69",
      ionizationEnergy = "2080.7 ",
      electronAffinity = "0.0",
      oxidationStates = "0",
      density = "0.8999",
      meltingPoint = "24.56",
      boilingPoint = "27.07"
   )

   val sodioDetails = ChemicalElementDetails(
      elementId = 10,
      R.drawable.sodio,
      series = R.string.alkali_metals,
      period = 3,
      group = 1,
      yearDiscovered = "1807",
      standardState = R.string.standard_state_solid,
      description = R.string.sodio_desc,
      electronicConfiguration = "[Ne] 3s¹",
      atomicMass = "22.98976928(2)",
      electronegativity = "0.93",
      atomicRadius = "154",
      ionizationEnergy = "495.8",
      electronAffinity = "52.8",
      oxidationStates = "+1",
      density = "968.0",
      meltingPoint = "370.95",
      boilingPoint = "1156.0"
   )

   val magnesioDetails = ChemicalElementDetails(
      elementId = 11,
      R.drawable.magnesio,
      series = R.string.series_alkaline_earth_metal,
      period = 3,
      group = 2,
      yearDiscovered = "1755",
      standardState = R.string.standard_state_solid,
      description = R.string.magnesio_desc,
      electronicConfiguration = "[Ne] 3s²",
      atomicMass = "24.3050(6)",
      electronegativity = "1.31",
      atomicRadius = "130",
      ionizationEnergy = "737.7",
      electronAffinity = "0.0",
      oxidationStates = "+2, +1",
      density = "1738.0",
      meltingPoint = "923.0",
      boilingPoint = "1363.0"
   )

   val aluminioDetails = ChemicalElementDetails(
      elementId = 12,
      R.drawable.aluminio,
      series = R.string.series_post_transition_metal,
      period = 3,
      group = 13,
      yearDiscovered = "1827",
      standardState = R.string.standard_state_solid,
      description = R.string.aluminio_desc,
      electronicConfiguration = "[Ne] 3s² 3p¹",
      atomicMass = "26.9815386(8)",
      electronegativity = "1.61",
      atomicRadius = "121",
      ionizationEnergy = "577.5",
      electronAffinity = "42.5",
      oxidationStates = "+3, +1",
      density = "2697.0",
      meltingPoint = "933.47",
      boilingPoint = "2792.0"
   )

   val silicioDetails = ChemicalElementDetails(
      elementId = 13,
      R.drawable.silicio,
      series = R.string.series_semimetal,
      period = 3,
      group = 14,
      yearDiscovered = "1823",
      standardState = R.string.standard_state_solid,
      description = R.string.silicio_desc,
      electronicConfiguration = "[Ne] 3s² 3p²",
      atomicMass = "28.0855(3)",
      electronegativity = "1.90",
      atomicRadius = "111",
      ionizationEnergy = "786.5",
      electronAffinity = "1336.0",
      oxidationStates = "+4, +1",
      density = "2330.0",
      meltingPoint = "1687.0",
      boilingPoint = "3538.0"
   )

   val fosforoDetails = ChemicalElementDetails(
      elementId = 14,
      R.drawable.fosforo,
      series = R.string.series_polyatomic_nonmetal,
      period = 3,
      group = 15,
      yearDiscovered = "1669",
      standardState = R.string.standard_state_solid,
      description = R.string.fosforo_desc,
      electronicConfiguration = "[Ne] 3s² 3p³",
      atomicMass = "30.973762(2)",
      electronegativity = "2.19",
      atomicRadius = "106",
      ionizationEnergy = "1011.8",
      electronAffinity = "72.0",
      oxidationStates = "+5, +4, ±3, ±2, ±1",
      density = "1823.0",
      meltingPoint = "317.3",
      boilingPoint = "553.6"
   )

   val enxofreDetails = ChemicalElementDetails(
      elementId = 15,
      R.drawable.enxofre,
      series = R.string.series_polyatomic_nonmetal,
      period = 3,
      group = 16,
      yearDiscovered = "1770",
      standardState = R.string.standard_state_solid,
      description = R.string.enxofre_desc,
      electronicConfiguration = "[Ne] 3s² 3p⁴",
      atomicMass = "32.065(5)",
      electronegativity = "2.58",
      atomicRadius = "102",
      ionizationEnergy = "999.6",
      electronAffinity = "200.0",
      oxidationStates = "+6, +4, ±2",
      density = "1960.0",
      meltingPoint = "388.36",
      boilingPoint = "717.75"
   )

   val cloroDetails = ChemicalElementDetails(
      elementId = 16,
      R.drawable.cloro,
      series = R.string.series_diatomic_nonmetal,
      period = 3,
      group = 17,
      yearDiscovered = "1774",
      standardState = R.string.standard_state_gas,
      description = R.string.cloro_desc,
      electronicConfiguration = "[Ne] 3s² 3p⁵",
      atomicMass = "35.453(2)",
      electronegativity = "3.16",
      atomicRadius = "99",
      ionizationEnergy = "1251.2",
      electronAffinity = "349.0",
      oxidationStates = "+7, +5, +3, ±1",
      density = "3.214",
      meltingPoint = "171.6",
      boilingPoint = "239.11"
   )

   val argonioDetails = ChemicalElementDetails(
      elementId = 17,
      R.drawable.argonio,
      series = R.string.series_noble_gas,
      period = 3,
      group = 18,
      yearDiscovered = "1894",
      standardState = R.string.standard_state_gas,
      description = R.string.argonio_desc,
      electronicConfiguration = "[Ne] 3s² 3p⁶",
      atomicMass = "39.948(1)",
      electronegativity = "0.0",
      atomicRadius = "97",
      ionizationEnergy = "1520.6",
      electronAffinity = "0.0",
      oxidationStates = "0",
      density = "1.784",
      meltingPoint = "83.80",
      boilingPoint = "87.30"
   )

   val potassioDetails = ChemicalElementDetails(
      elementId = 18,
      R.drawable.potassio,
      series = R.string.series_alkali_metal,
      period = 4,
      group = 1,
      yearDiscovered = "1807",
      standardState = R.string.standard_state_solid,
      description = R.string.potassio_desc,
      electronicConfiguration = "[Ar] 4s¹",
      atomicMass = "39.0983(1)",
      electronegativity = "0.82",
      atomicRadius = "196",
      ionizationEnergy = "418.8",
      electronAffinity = "48.4",
      oxidationStates = "+1",
      density = "856.0",
      meltingPoint = "336.53",
      boilingPoint = "1032.0"
   )

   val calcioDetails = ChemicalElementDetails(
      elementId = 19,
      R.drawable.calcio,
      series = R.string.series_alkaline_earth_metal,
      period = 4,
      group = 2,
      yearDiscovered = "1808",
      standardState = R.string.standard_state_solid,
      description = R.string.calcio_desc,
      electronicConfiguration = "[Ar] 4s²",
      atomicMass = "40.078(4)",
      electronegativity = "1.0",
      atomicRadius = "174",
      ionizationEnergy = "589.8",
      electronAffinity = "2.37",
      oxidationStates = "+2",
      density = "1550.0",
      meltingPoint = "1115.0",
      boilingPoint = "1757.0"
   )

   val escandioDetails = ChemicalElementDetails(
      elementId = 20,
      R.drawable.escandio,
      series = R.string.series_transition_metal,
      period = 4,
      group = 3,
      yearDiscovered = "1879",
      standardState = R.string.standard_state_solid,
      description = R.string.escandio_desc,
      electronicConfiguration = "[Ar] 3d¹ 4s²",
      atomicMass = "44.955912(6)",
      electronegativity = "1.36",
      atomicRadius = "144",
      ionizationEnergy = "633.1",
      electronAffinity = "18.1",
      oxidationStates = "+3",
      density = "1550.0",
      meltingPoint = "1814.0",
      boilingPoint = "3109.0"
   )

   val titanioDetails = ChemicalElementDetails(
      elementId = 21,
      R.drawable.titanio,
      series = R.string.series_transition_metal,
      period = 4,
      group = 4,
      yearDiscovered = "1791",
      standardState = R.string.standard_state_solid,
      description = R.string.titanio_desc,
      electronicConfiguration = "[Ar] 3d² 4s²",
      atomicMass = "47.867(1)",
      electronegativity = "1.54",
      atomicRadius = "136",
      ionizationEnergy = "658.8",
      electronAffinity = "7.6",
      oxidationStates = "+4",
      density = "4507.0",
      meltingPoint = "1941.0",
      boilingPoint = "3560.0"
   )

   val vanadioDetails = ChemicalElementDetails(
      elementId = 22,
      R.drawable.vanadio,
      series = R.string.series_transition_metal,
      period = 4,
      group = 5,
      yearDiscovered = "1830",
      standardState = R.string.standard_state_solid,
      description = R.string.vanadio_desc,
      electronicConfiguration = "[Ar] 3d³ 4s²",
      atomicMass = "50.9415(1)",
      electronegativity = "1.63",
      atomicRadius = "125",
      ionizationEnergy = "650.9",
      electronAffinity = "50.6",
      oxidationStates = "+5, +4, +3, +2, ±1",
      density = "6110.0",
      meltingPoint = "2183.0",
      boilingPoint = "3680.0"
   )

   val cromoDetails = ChemicalElementDetails(
      elementId = 23,
      R.drawable.cromo,
      series = R.string.series_transition_metal,
      period = 4,
      group = 6,
      yearDiscovered = "1797",
      standardState = R.string.standard_state_solid,
      description = R.string.cromo_desc,
      electronicConfiguration = "[Ar] 3d⁵ 4s²",
      atomicMass = "51.9961",
      electronegativity = "1.66",
      atomicRadius = "127",
      ionizationEnergy = "652.9",
      electronAffinity = "64.3",
      oxidationStates = "+6, +5, +4, +3, ±2, ±1",
      density = "7200.0",
      meltingPoint = "2180.0",
      boilingPoint = "2944.0"
   )

   val manganesDetails = ChemicalElementDetails(
      elementId = 24,
      R.drawable.manganes,
      series = R.string.series_transition_metal,
      period = 4,
      group = 7,
      yearDiscovered = "1774",
      standardState = R.string.standard_state_solid,
      description = R.string.manganes_desc,
      electronicConfiguration = "[Ar] 4s² 3d⁵",
      atomicMass = "54.938045(5)",
      electronegativity = "1.55",
      atomicRadius = "139",
      ionizationEnergy = "717.3",
      electronAffinity = "0.0",
      oxidationStates = "+7, +6, +5, +4, ±3, ±2, ±1",
      density = "7470.0",
      meltingPoint = "1519.0",
      boilingPoint = "2334.0"
   )

   val ferroDetails = ChemicalElementDetails(
      elementId = 25,
      R.drawable.ferro,
      series = R.string.series_transition_metal,
      period = 4,
      group = 8,
      yearDiscovered = "5000 a.C",
      standardState = R.string.standard_state_solid,
      description = R.string.ferro_desc,
      electronicConfiguration = "[Ar] 3d⁶ 4s²",
      atomicMass = "55.845(2)",
      electronegativity = "1.83",
      atomicRadius = "125",
      ionizationEnergy = "762.5",
      electronAffinity = "15.7",
      oxidationStates = "+6, +4, +3, +2",
      density = "7874.0",
      meltingPoint = "1811.0",
      boilingPoint = "3134.0"
   )

   val cobaltoDetails = ChemicalElementDetails(
      elementId = 26,
      R.drawable.cobalto,
      series = R.string.series_transition_metal,
      period = 4,
      group = 9,
      yearDiscovered = "1730",
      standardState = R.string.standard_state_solid,
      description = R.string.cobalto_desc,
      electronicConfiguration = "[Ar] 3d⁷ 4s²",
      atomicMass = "58.933195(5)",
      electronegativity = "1.88",
      atomicRadius = "152",
      ionizationEnergy = "760.4",
      electronAffinity = "15.7",
      oxidationStates = "+3, +2",
      density = "8900.0",
      meltingPoint = "1768.0",
      boilingPoint = "3200.0"
   )
   
   val niquelDetails = ChemicalElementDetails(
      elementId = 27,
      R.drawable.niquel,
      series = R.string.series_transition_metal,
      period = 4,
      group = 10,
      yearDiscovered = "1751",
      standardState = R.string.standard_state_solid,
      description = R.string.niquel_desc,
      electronicConfiguration = "[Ar] 4s¹ 3d⁹",
      atomicMass = "58.6934(4)",
      electronegativity = "1.91",
      atomicRadius = "124",
      ionizationEnergy = "737.1",
      electronAffinity = "112.0",
      oxidationStates = "+4, +3, +2, ±1",
      density = "8908.0",
      meltingPoint = "1728.0",
      boilingPoint = "3186.0"
   )

   val cobreDetails = ChemicalElementDetails(
      elementId = 28,
      R.drawable.cobre,
      series = R.string.series_transition_metal,
      period = 4,
      group = 11,
      yearDiscovered = "9000 a.C",
      standardState = R.string.standard_state_solid,
      description = R.string.cobre_desc,
      electronicConfiguration = "[Ar] 3d¹⁰ 4s¹",
      atomicMass = "63.546",
      electronegativity = "1.9",
      atomicRadius = "132",
      ionizationEnergy = "745.5",
      electronAffinity = "118.4",
      oxidationStates = "+4, +3, +2, +1",
      density = "8920.0",
      meltingPoint = "1357.77",
      boilingPoint = "2835.0"
   )

   val zincoDetails = ChemicalElementDetails(
      elementId = 29,
      R.drawable.zinco,
      series = R.string.series_transition_metal,
      period = 4,
      group = 12,
      yearDiscovered = "1746",
      standardState = R.string.standard_state_solid,
      description = R.string.zinco_desc,
      electronicConfiguration = "[Ar] 3d¹⁰ 4s²",
      atomicMass = "65.38(2)",
      electronegativity = "1.65",
      atomicRadius = "122",
      ionizationEnergy = "906.4",
      electronAffinity = "0.0",
      oxidationStates = "+2, +1, 0",
      density = "7140.0",
      meltingPoint = "692.68",
      boilingPoint = "1180.0"
   )

   val galioDetails = ChemicalElementDetails(
      elementId = 30,
      R.drawable.galio,
      series = R.string.series_post_transition_metal,
      period = 4,
      group = 13,
      yearDiscovered = "1875",
      standardState = R.string.standard_state_solid,
      description = R.string.galio_desc,
      electronicConfiguration = "[Ar] 4s² 3d¹⁰ 4p¹",
      atomicMass = "69.723",
      electronegativity = "1.81",
      atomicRadius = "122",
      ionizationEnergy = "578.8",
      electronAffinity = "28.9",
      oxidationStates = "+3, +2, +1",
      density = "5904.0",
      meltingPoint = "302.92",
      boilingPoint = "2477.0"
   )
   
   val germanioDetails = ChemicalElementDetails(
      elementId = 31,
      R.drawable.germanio,
      series = R.string.series_semimetal,
      period = 4,
      group = 14,
      yearDiscovered = "1886",
      standardState = R.string.standard_state_solid,
      description = R.string.germanio_desc,
      electronicConfiguration = "[Ar] 4s² 3d¹⁰ 4p²",
      atomicMass = "72.64",
      electronegativity = "2.01",
      atomicRadius = "122",
      ionizationEnergy = "762.0",
      electronAffinity = "119.0",
      oxidationStates = "±4, ±3, ±2, ±1, 0",
      density = "5323.0",
      meltingPoint = "1211.40",
      boilingPoint = "3106.0"
   )

   val arsenioDetails = ChemicalElementDetails(
      elementId = 32,
      R.drawable.arsenio,
      series = R.string.series_semimetal,
      period = 4,
      group = 15,
      yearDiscovered = "1250",
      standardState = R.string.standard_state_solid,
      description = R.string.arsenio_desc,
      electronicConfiguration = "[Ar] 4s² 3d¹⁰ 4p³",
      atomicMass = "74.92",
      electronegativity = "2.18",
      atomicRadius = "119",
      ionizationEnergy = "947.0",
      electronAffinity = "78.0",
      oxidationStates = "5, ±3, +2, +1",
      density = "5727.0",
      meltingPoint = "1090.0",
      boilingPoint = "887.0"
   )

   val selenioDetails = ChemicalElementDetails(
      elementId = 33,
      R.drawable.selenio,
      series = R.string.series_polyatomic_nonmetal,
      period = 4,
      group = 16,
      yearDiscovered = "1817",
      standardState = R.string.standard_state_solid,
      description = R.string.selenio_desc,
      electronicConfiguration = "[Ar] 4s² 3d¹⁰ 4p⁴",
      atomicMass = "78.96",
      electronegativity = "2.55",
      atomicRadius = "120",
      ionizationEnergy = "941.0",
      electronAffinity = "195.0",
      oxidationStates = "+6, +4, ±2, 1",
      density = "4790.0",
      meltingPoint = "494.0",
      boilingPoint = "958.0"
   )

   val bromoDetails = ChemicalElementDetails(
      elementId = 34,
      R.drawable.bromo,
      series = R.string.series_diatomic_nonmetal,
      period = 4,
      group = 17,
      yearDiscovered = "1826",
      standardState = R.string.standard_state_gas,
      description = R.string.bromo_desc,
      electronicConfiguration = "[Ar] 4s² 3d¹⁰ 4p⁵",
      atomicMass = "79.904",
      electronegativity = "2.96",
      atomicRadius = "120",
      ionizationEnergy = "1139.9",
      electronAffinity = "325.0",
      oxidationStates = "+7, +5, +4, +3, ±1",
      density = "3119.0",
      meltingPoint = "265.8",
      boilingPoint = "332.0"
   )

   val criptonioDetails = ChemicalElementDetails(
      elementId = 35,
      R.drawable.criptonio,
      series = R.string.series_noble_gas,
      period = 4,
      group = 18,
      yearDiscovered = "1898",
      standardState = R.string.standard_state_gas,
      description = R.string.criptonio_desc,
      electronicConfiguration = "[Ar] 4s² 3d¹⁰ 4p⁶",
      atomicMass = "83.798",
      electronegativity = "3.0",
      atomicRadius = "116",
      ionizationEnergy = "1350.8",
      electronAffinity = "???",
      oxidationStates = "+2",
      density = "3.708",
      meltingPoint = "115.79",
      boilingPoint = "119.93"
   )

   val rubidioDetails = ChemicalElementDetails(
      elementId = 36,
      R.drawable.rubidio,
      series = R.string.series_alkali_metal,
      period = 5,
      group = 1,
      yearDiscovered = "1861",
      standardState = R.string.standard_state_liquid,
      description = R.string.rubidio_desc,
      electronicConfiguration = "[Kr] 5s¹",
      atomicMass = "85.4678(3)",
      electronegativity = "0.82",
      atomicRadius = "211",
      ionizationEnergy = "403.0",
      electronAffinity = "46.9",
      oxidationStates = "+1",
      density = "1532.0",
      meltingPoint = "312.46",
      boilingPoint = "961.0"
   )

   val estroncioDetails = ChemicalElementDetails(
      elementId = 37,
      R.drawable.estroncio,
      series = R.string.series_alkaline_earth_metal,
      period = 5,
      group = 2,
      yearDiscovered = "1790",
      standardState = R.string.standard_state_solid,
      description = R.string.estroncio_desc,
      electronicConfiguration = "[Kr] 5s²",
      atomicMass = "87.62(1)",
      electronegativity = "0.95",
      atomicRadius = "192",
      ionizationEnergy = "549.5",
      electronAffinity = "5.03",
      oxidationStates = "+2",
      density = "2630.0",
      meltingPoint = "1050.0",
      boilingPoint = "1655.0"
   )

   val itrioDetails = ChemicalElementDetails(
      elementId = 38,
      R.drawable.itrio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 3,
      yearDiscovered = "1794",
      standardState = R.string.standard_state_solid,
      description = R.string.itrio_desc,
      electronicConfiguration = "[Kr] 4d¹ 5s²",
      atomicMass = "88.90584(2)",
      electronegativity = "1.22",
      atomicRadius = "190",
      ionizationEnergy = "600.0",
      electronAffinity = "29.6",
      oxidationStates = "+3, +2, +1",
      density = "4472.0",
      meltingPoint = "1799.0",
      boilingPoint = "3609.0"
   )

   val zirconioDetails = ChemicalElementDetails(
      elementId = 39,
      R.drawable.zirconio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 4,
      yearDiscovered = "1789",
      standardState = R.string.standard_state_solid,
      description = R.string.zirconio_desc,
      electronicConfiguration = "[Kr] 5s² 4d²",
      atomicMass = "91.224",
      electronegativity = "1.33",
      atomicRadius = "175",
      ionizationEnergy = "640.1",
      electronAffinity = "41.1",
      oxidationStates = "+4, +3, +2, +1",
      density = "6511.0",
      meltingPoint = "2128.0",
      boilingPoint = "4682.0"
   )
   
   val niobioDetails = ChemicalElementDetails(
      elementId = 40,
      R.drawable.niobio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 5,
      yearDiscovered = "1801",
      standardState = R.string.standard_state_solid,
      description = R.string.niobio_desc,
      electronicConfiguration = "[Kr] 4d³ 5s²",
      atomicMass = "92.90638",
      electronegativity = "1.6",
      atomicRadius = "164",
      ionizationEnergy = "652.1",
      electronAffinity = "86.1",
      oxidationStates = "+5, +4, +3, +2, -1",
      density = "8570.0",
      meltingPoint = "2750.0",
      boilingPoint = "5017.0"
   )

   val molibdenioDetails = ChemicalElementDetails(
      elementId = 41,
      R.drawable.molibdenio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 6,
      yearDiscovered = "1778",
      standardState = R.string.standard_state_solid,
      description = R.string.molibdenio_desc,
      electronicConfiguration = "[Kr] 5s¹ 4d⁵",
      atomicMass = "95.96",
      electronegativity = "2.16",
      atomicRadius = "154",
      ionizationEnergy = "684.3",
      electronAffinity = "71.9",
      oxidationStates = "+6, +5, +4, +3, ±2, ±1",
      density = "10280.0",
      meltingPoint = "2436.0",
      boilingPoint = "4912.0"
   )

   val tecnecioDetails = ChemicalElementDetails(
      elementId = 42,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 5,
      group = 7,
      yearDiscovered = "1937",
      standardState = R.string.standard_state_solid,
      description = R.string.tecnecio_desc,
      electronicConfiguration = "[Kr] 5s² 4d⁵",
      atomicMass = "98",
      electronegativity = "1.9",
      atomicRadius = "147",
      ionizationEnergy = "702.0",
      electronAffinity = "96",
      oxidationStates = "+7, +6, +5, +4, ±3, +2, ±1",
      density = "11500.0",
      meltingPoint = "2430.0",
      boilingPoint = "4538.0"
   )

   val rutenioDetails = ChemicalElementDetails(
      elementId = 43,
      R.drawable.rutenio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 8,
      yearDiscovered = "1844",
      standardState = R.string.standard_state_solid,
      description = R.string.rutenio_desc,
      electronicConfiguration = "[Kr] 5s¹ 4d⁷",
      atomicMass = "101.07",
      electronegativity = "2.2",
      atomicRadius = "146",
      ionizationEnergy = "710.2",
      electronAffinity = "101.3",
      oxidationStates = "+8, +7, +6, +4, +3, ±2, +1",
      density = "12370.0",
      meltingPoint = "2607.0",
      boilingPoint = "4423.0"
   )

   val rodioDetails = ChemicalElementDetails(
      elementId = 44,
      R.drawable.rodio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 9,
      yearDiscovered = "1803",
      standardState = R.string.standard_state_solid,
      description = R.string.rodio_desc,
      electronicConfiguration = "[Kr] 5s¹ 4d⁸",
      atomicMass = "102.90550",
      electronegativity = "2.28",
      atomicRadius = "142",
      ionizationEnergy = "719.7",
      electronAffinity = "109.7",
      oxidationStates = "+6, +5, +4, +3, +2, ±1",
      density = "12450.0",
      meltingPoint = "2237.0",
      boilingPoint = "3968.0"
   )

   val paladioDetails = ChemicalElementDetails(
      elementId = 45,
      R.drawable.paladio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 10,
      yearDiscovered = "1802",
      standardState = R.string.standard_state_solid,
      description = R.string.paladio_desc,
      electronicConfiguration = "[Kr] 4d¹⁰",
      atomicMass = "106.42",
      electronegativity = "2.2",
      atomicRadius = "139",
      ionizationEnergy = "804.4",
      electronAffinity = "53.7",
      oxidationStates = "+6, +4, +2, +1, 0",
      density = "12023.0",
      meltingPoint = "1828.05",
      boilingPoint = "3236.0"
   )

   val prataDetails = ChemicalElementDetails(
      elementId = 46,
      R.drawable.prata,
      series = R.string.series_transition_metal,
      period = 5,
      group = 11,
      yearDiscovered = "5000 a.C",
      standardState = R.string.standard_state_solid,
      description = R.string.prata_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s¹",
      atomicMass = "107.8682",
      electronegativity = "1.93",
      atomicRadius = "139",
      ionizationEnergy = "145.0",
      electronAffinity = "125.6",
      oxidationStates = "+3, +2, +1",
      density = "10490.0",
      meltingPoint = "1234.93",
      boilingPoint = "2435.0"
   )

   val cadmioDetails = ChemicalElementDetails(
      elementId = 47,
      R.drawable.cadmio,
      series = R.string.series_transition_metal,
      period = 5,
      group = 12,
      yearDiscovered = "1817",
      standardState = R.string.standard_state_solid,
      description = R.string.cadmio_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s²",
      atomicMass = "112.411",
      electronegativity = "1.69",
      atomicRadius = "144",
      ionizationEnergy = "867.8",
      electronAffinity = "0",
      oxidationStates = "+2, +1",
      density = "8650.0",
      meltingPoint = "594.22",
      boilingPoint = "1040.0"
   )

   val indioDetails = ChemicalElementDetails(
      elementId = 48,
      R.drawable.indio,
      series = R.string.post_transition_metals,
      period = 5,
      group = 13,
      yearDiscovered = "1863",
      standardState = R.string.standard_state_solid,
      description = R.string.indio_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s² 5p¹",
      atomicMass = "114.818",
      electronegativity = "1.78",
      atomicRadius = "142",
      ionizationEnergy = "558.3",
      electronAffinity = "28.9",
      oxidationStates = "+3, +2, +1",
      density = "7310.0",
      meltingPoint = "429.75",
      boilingPoint = "2345.0"
   )

   val estanhoDetails = ChemicalElementDetails(
      elementId = 49,
      R.drawable.estanho,
      series = R.string.post_transition_metals,
      period = 5,
      group = 14,
      yearDiscovered = "700 a.C.",
      standardState = R.string.standard_state_solid,
      description = R.string.estanho_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s² 5p²",
      atomicMass = "118.71",
      electronegativity = "1.96",
      atomicRadius = "139",
      ionizationEnergy = "708.6",
      electronAffinity = "107.3",
      oxidationStates = "±4, +2",
      density = "7310.0",
      meltingPoint = "505.08",
      boilingPoint = "2875.0"
   )
   
   val antimonioDetails = ChemicalElementDetails(
      elementId = 50,
      R.drawable.antimonio,
      series = R.string.series_semimetal,
      period = 5,
      group = 15,
      yearDiscovered = "1450",
      standardState = R.string.standard_state_solid,
      description = R.string.antimonio_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s² 5p³",
      atomicMass = "121.760",
      electronegativity = "2.05",
      atomicRadius = "139",
      ionizationEnergy = "834.0",
      electronAffinity = "103.2",
      oxidationStates = "+5, ±3",
      density = "6697.0",
      meltingPoint = "903.78",
      boilingPoint = "1860.0"
   )
   
   val telurioDetails = ChemicalElementDetails(
      elementId = 51,
      R.drawable.telurio,
      series = R.string.series_semimetal,
      period = 5,
      group = 16,
      yearDiscovered = "1782",
      standardState = R.string.standard_state_solid,
      description = R.string.telurio_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s² 5p⁴",
      atomicMass = "127.6",
      electronegativity = "2.1",
      atomicRadius = "138",
      ionizationEnergy = "869.3",
      electronAffinity = "190.2",
      oxidationStates = "+6, +5, +4, ±2",
      density = "6240.0",
      meltingPoint = "722.66",
      boilingPoint = "1261.0"
   )

   val iodoDetails = ChemicalElementDetails(
      elementId = 52,
      R.drawable.iodo,
      series = R.string.series_diatomic_nonmetal,
      period = 5,
      group = 17,
      yearDiscovered = "1811",
      standardState = R.string.standard_state_solid,
      description = R.string.iodo_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s² 5p⁵",
      atomicMass = "126.90447",
      electronegativity = "2.66",
      atomicRadius = "139",
      ionizationEnergy = "1008.4",
      electronAffinity = "298.4",
      oxidationStates = "+7, +5, +3, ±1",
      density = "4940.0",
      meltingPoint = "386.85",
      boilingPoint = "457.6"
   )

   val xenonioDetails = ChemicalElementDetails(
      elementId = 53,
      R.drawable.xenonio,
      series = R.string.series_noble_gas,
      period = 5,
      group = 18,
      yearDiscovered = "1898",
      standardState = R.string.standard_state_gas,
      description = R.string.xenonio_desc,
      electronicConfiguration = "[Kr] 4d¹⁰ 5s² 5p⁶",
      atomicMass = "131.293",
      electronegativity = "2.6",
      atomicRadius = "130",
      ionizationEnergy = "1170.4",
      electronAffinity = "0",
      oxidationStates = "0",
      density = "5.9",
      meltingPoint = "161.36",
      boilingPoint = "165.03"
   )

   val cesioDetails = ChemicalElementDetails(
      elementId = 54,
      R.drawable.cesio,
      series = R.string.series_alkali_metal,
      period = 6,
      group = 1,
      yearDiscovered = "1860",
      standardState = R.string.standard_state_liquid,
      description = R.string.cesio_desc,
      electronicConfiguration = "[Xe] 6s¹",
      atomicMass = "132.9054519(2)",
      electronegativity = "0.79",
      atomicRadius = "225",
      ionizationEnergy = "375.7",
      electronAffinity = "45.5",
      oxidationStates = "+1",
      density = "1879.0",
      meltingPoint = "301.6",
      boilingPoint = "944.0"
   )

   val barioDetails = ChemicalElementDetails(
      elementId = 55,
      R.drawable.bario,
      series = R.string.series_alkaline_earth_metal,
      period = 6,
      group = 3,
      yearDiscovered = "1808",
      standardState = R.string.standard_state_solid,
      description = R.string.bario_desc,
      electronicConfiguration = "[Xe] 6s²",
      atomicMass = "137.327(7)",
      electronegativity = "0.89",
      atomicRadius = "215",
      ionizationEnergy = "502.9",
      electronAffinity = "13.95",
      oxidationStates = "+2",
      density = "3510.0",
      meltingPoint = "1000.0",
      boilingPoint = "2170.0"
   )

   val hafnioDetails = ChemicalElementDetails(
      elementId = 57,
      R.drawable.hafnio,
      series = R.string.series_transition_metal,
      period = 6,
      group = 4,
      yearDiscovered = "1923",
      standardState = R.string.standard_state_solid,
      description = R.string.hafnio_desc,
      electronicConfiguration = "[Xe] 6s² 5d² 4f¹⁴",
      atomicMass = "178.49(2)",
      electronegativity = "1.3",
      atomicRadius = "175",
      ionizationEnergy = "658.5",
      electronAffinity = "86.1",
      oxidationStates = "+4",
      density = "13310.0",
      meltingPoint = "2506.0",
      boilingPoint = "4876.0"
   )

   val tantaloDetails = ChemicalElementDetails(
      elementId = 59,
      R.drawable.tantalo,
      series = R.string.series_transition_metal,
      period = 6,
      group = 5,
      yearDiscovered = "1802",
      standardState = R.string.standard_state_solid,
      description = R.string.tantalo_desc,
      electronicConfiguration = "[Xe] 6s² 5d³ 4f¹⁴",
      atomicMass = "180.94788(2)",
      electronegativity = "1.5",
      atomicRadius = "138",
      ionizationEnergy = "761.0",
      electronAffinity = "31.0",
      oxidationStates = "+5, +4, +3, +2, -1",
      density = "16650.0",
      meltingPoint = "3290.0",
      boilingPoint = "5731.0"
   )

   val tungstenioDetails = ChemicalElementDetails(
      elementId = 60,
      R.drawable.tungstenio,
      series = R.string.series_transition_metal,
      period = 6,
      group = 6,
      yearDiscovered = "1781",
      standardState = R.string.standard_state_solid,
      description = R.string.tungstenio_desc,
      electronicConfiguration = "[Xe] 6s² 5d⁴ 4f¹⁴",
      atomicMass = "183.84(1)",
      electronegativity = "2.36",
      atomicRadius = "146",
      ionizationEnergy = "770.0",
      electronAffinity = "78.6",
      oxidationStates = "+6, +5, +4, +3, +2",
      density = "19250.0",
      meltingPoint = "3695.0",
      boilingPoint = "5828.0"
   )

   val renioDetails = ChemicalElementDetails(
      elementId = 61,
      R.drawable.renio,
      series = R.string.series_transition_metal,
      period = 6,
      group = 7,
      yearDiscovered = "1925",
      standardState = R.string.standard_state_solid,
      description = R.string.renio_desc,
      electronicConfiguration = "[Xe] 6s² 5d⁵ 4f¹⁴",
      atomicMass = "186.207(1)",
      electronegativity = "1.9",
      atomicRadius = "159",
      ionizationEnergy = "760.0",
      electronAffinity = "14.5",
      oxidationStates = "+6, +4, ±2",
      density = "21020.0",
      meltingPoint = "3459.0",
      boilingPoint = "5869.0"
   )

   val osmioDetails = ChemicalElementDetails(
      elementId = 62,
      R.drawable.osmio,
      series = R.string.series_transition_metal,
      period = 6,
      group = 8,
      yearDiscovered = "1802",
      standardState = R.string.standard_state_solid,
      description = R.string.osmio_desc,
      electronicConfiguration = "[Xe] 6s² 5d⁶ 4f¹⁴",
      atomicMass = "190.23(3)",
      electronegativity = "1.9",
      atomicRadius = "128",
      ionizationEnergy = "840.0",
      electronAffinity = "106.1",
      oxidationStates = "+(8 - 3), ±2, ±1, 0",
      density = "22610.0",
      meltingPoint = "3306.0",
      boilingPoint = "5285.0"
   )

   val iridioDetails = ChemicalElementDetails(
      elementId = 63,
      R.drawable.iridio,
      series = R.string.series_transition_metal,
      period = 6,
      group = 9,
      yearDiscovered = "1803",
      standardState = R.string.standard_state_solid,
      description = R.string.iridio_desc,
      electronicConfiguration = "[Xe] 6s² 5d⁷ 4f¹⁴",
      atomicMass = "192.217(3)",
      electronegativity = "2.2",
      atomicRadius = "137",
      ionizationEnergy = "880.0",
      electronAffinity = "151.1",
      oxidationStates = "+6, +5, +4, ±3, +2, ±1, 0",
      density = "22650.0",
      meltingPoint = "2719.0",
      boilingPoint = "4701.0"
   )

   val platinaDetails = ChemicalElementDetails(
      elementId = 64,
      R.drawable.platina,
      series = R.string.series_transition_metal,
      period = 6,
      group = 10,
      yearDiscovered = "1735",
      standardState = R.string.standard_state_solid,
      description = R.string.platina_desc,
      electronicConfiguration = "[Xe] 6s² 5d⁹ 4f¹⁴",
      atomicMass = "195.084(9)",
      electronegativity = "2.28",
      atomicRadius = "128",
      ionizationEnergy = "870.0",
      electronAffinity = "205.3",
      oxidationStates = "+6, +5, +4, +3, ±2, ±1",
      density = "21090.0",
      meltingPoint = "2041.15",
      boilingPoint = "4098.0"
   )

   val ouroDetails = ChemicalElementDetails(
      elementId = 65,
      R.drawable.ouro,
      series = R.string.series_transition_metal,
      period = 6,
      group = 11,
      yearDiscovered = "5000 a.C.",
      standardState = R.string.standard_state_solid,
      description = R.string.ouro_desc,
      electronicConfiguration = "[Xe] 6s¹ 5d¹⁰ 4f¹⁴",
      atomicMass = "196.966569(4)",
      electronegativity = "2.54",
      atomicRadius = "144",
      ionizationEnergy = "890.1",
      electronAffinity = "222.8",
      oxidationStates = "+3, +1",
      density = "19300.0",
      meltingPoint = "1337.33",
      boilingPoint = "3129.0"
   )

   val mercurioDetails = ChemicalElementDetails(
      elementId = 66,
      R.drawable.mercurio,
      series = R.string.series_transition_metal,
      period = 6,
      group = 12,
      yearDiscovered = "1500 a.C.",
      standardState = R.string.standard_state_liquid,
      description = R.string.mercurio_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴",
      atomicMass = "200.59(2)",
      electronegativity = "2.0",
      atomicRadius = "149",
      ionizationEnergy = "1007.1",
      electronAffinity = "0",
      oxidationStates = "+2, +1",
      density = "13579.0",
      meltingPoint = "234.32",
      boilingPoint = "629.88"
   )

   val talioDetails = ChemicalElementDetails(
      elementId = 67,
      R.drawable.talio,
      series = R.string.series_post_transition_metal,
      period = 6,
      group = 13,
      yearDiscovered = "1861",
      standardState = R.string.standard_state_solid,
      description = R.string.talio_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴ 6p¹",
      atomicMass = "204.3833(2)",
      electronegativity = "1.62",
      atomicRadius = "170",
      ionizationEnergy = "589.4",
      electronAffinity = "19.2",
      oxidationStates = "+3, +1",
      density = "11850.0",
      meltingPoint = "577.0",
      boilingPoint = "1746.0"
   )

   val chumboDetails = ChemicalElementDetails(
      elementId = 68,
      R.drawable.chumbo,
      series = R.string.series_post_transition_metal,
      period = 6,
      group = 14,
      yearDiscovered = "3800 a.C.",
      standardState = R.string.standard_state_solid,
      description = R.string.chumbo_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴ 6p²",
      atomicMass = "207.2(1)",
      electronegativity = "1.9",
      atomicRadius = "147",
      ionizationEnergy = "715.6",
      electronAffinity = "35.1",
      oxidationStates = "+4, +2",
      density = "11340.0",
      meltingPoint = "600.61",
      boilingPoint = "2022.0"
   )

   val bismutoDetails = ChemicalElementDetails(
      elementId = 69,
      R.drawable.bismuto,
      series = R.string.series_post_transition_metal,
      period = 6,
      group = 15,
      yearDiscovered = "1753",
      standardState = R.string.standard_state_solid,
      description = R.string.bismuto_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴ 6p³",
      atomicMass = "208.98040",
      electronegativity = "2.02",
      atomicRadius = "148",
      ionizationEnergy = "703.0",
      electronAffinity = "91.2",
      oxidationStates = "+5, +3",
      density = "9780.0",
      meltingPoint = "544.7",
      boilingPoint = "1837.0"
   )

   val polonioDetails = ChemicalElementDetails(
      elementId = 70,
      R.drawable.polonio,
      series = R.string.series_post_transition_metal,
      period = 6,
      group = 16,
      yearDiscovered = "1898",
      standardState = R.string.standard_state_solid,
      description = R.string.polonio_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴ 6p⁴",
      atomicMass = "209",
      electronegativity = "2.0",
      atomicRadius = "190",
      ionizationEnergy = "812.1",
      electronAffinity = "183.3",
      oxidationStates = "±2",
      density = "9196.0",
      meltingPoint = "527.0",
      boilingPoint = "1235.0"
   )

   val astatoDetails = ChemicalElementDetails(
      elementId = 71,
      R.drawable.astato,
      series = R.string.series_semimetal,
      period = 6,
      group = 17,
      yearDiscovered = "1940",
      standardState = R.string.standard_state_solid,
      description = R.string.astato_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴ 6p⁵",
      atomicMass = "210",
      electronegativity = "2.2",
      atomicRadius = "127",
      ionizationEnergy = "920.0",
      electronAffinity = "183.3",
      oxidationStates = "+7, +5, +3, ±1",
      density = "?",
      meltingPoint = "575.0",
      boilingPoint = "610.0"
   )

   val radonioDetails = ChemicalElementDetails(
      elementId = 72,
      R.drawable.sem_foto,
      series = R.string.series_noble_gas,
      period = 6,
      group = 18,
      yearDiscovered = "1899",
      standardState = R.string.standard_state_gas,
      description = R.string.radonio_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹⁰ 4f¹⁴ 6p⁶",
      atomicMass = "222",
      electronegativity = "0.0",
      atomicRadius = "120",
      ionizationEnergy = "1037.0",
      electronAffinity = "0.0",
      oxidationStates = "+2",
      density = "9.73",
      meltingPoint = "202.0",
      boilingPoint = "211.3"
   )

   val francioDetails = ChemicalElementDetails(
      elementId = 73,
      R.drawable.sem_foto,
      series = R.string.series_alkali_metal,
      period = 7,
      group = 1,
      yearDiscovered = "1939",
      standardState = R.string.standard_state_solid,
      description = R.string.francio_desc,
      electronicConfiguration = "[Rn] 7s¹",
      atomicMass = "223.0197",
      electronegativity = "0.7",
      atomicRadius = "260",
      ionizationEnergy = "380.0",
      electronAffinity = "44.0",
      oxidationStates = "+1",
      density = "1870",
      meltingPoint = "300.0",
      boilingPoint = "950.0"
   )

   val radioDetails = ChemicalElementDetails(
      elementId = 74,
      R.drawable.sem_foto,
      series = R.string.series_alkaline_earth_metal,
      period = 7,
      group = 2,
      yearDiscovered = "1898",
      standardState = R.string.standard_state_solid,
      description = R.string.radio_desc,
      electronicConfiguration = "[Rn] 7s²",
      atomicMass = "226.0254",
      electronegativity = "1.0",
      atomicRadius = "221",
      ionizationEnergy = "509.3",
      electronAffinity = "0.0",
      oxidationStates = "+2",
      density = "5500",
      meltingPoint = "973.0",
      boilingPoint = "2010.0"
   )

   val rutherfordioDetails = ChemicalElementDetails(
      elementId = 75,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 7,
      group = 4,
      yearDiscovered = "1964",
      standardState = R.string.standard_state_solid,
      description = R.string.rutherfordio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d²",
      atomicMass = "267",
      electronegativity = "?",
      atomicRadius = "?",
      ionizationEnergy = "579.9",
      electronAffinity = "?",
      oxidationStates = "+4",
      density = "23000",
      meltingPoint = "2400.0",
      boilingPoint = "5800.0"
   )

   val dubnioDetails = ChemicalElementDetails(
      elementId = 76,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 7,
      group = 5,
      yearDiscovered = "1967",
      standardState = R.string.standard_state_solid,
      description = R.string.dubnio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d³",
      atomicMass = "268",
      electronegativity = "?",
      atomicRadius = "149",
      ionizationEnergy = "664.8",
      electronAffinity = "?",
      oxidationStates = "+5, +4, +3",
      density = "29000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val seaborgioDetails = ChemicalElementDetails(
      elementId = 77,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 7,
      group = 6,
      yearDiscovered = "1974",
      standardState = R.string.standard_state_solid,
      description = R.string.seaborgio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d⁴",
      atomicMass = "269",
      electronegativity = "?",
      atomicRadius = "143",
      ionizationEnergy = "757.5",
      electronAffinity = "?",
      oxidationStates = "+6, +5, +4, +3",
      density = "35000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val bohrioDetails = ChemicalElementDetails(
      elementId = 78,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 7,
      group = 7,
      yearDiscovered = "1976",
      standardState = R.string.standard_state_solid,
      description = R.string.bohrio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d⁵",
      atomicMass = "270",
      electronegativity = "?",
      atomicRadius = "141",
      ionizationEnergy = "742.9",
      electronAffinity = "?",
      oxidationStates = "+7, +5, +4, +3",
      density = "37000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val hassioDetails = ChemicalElementDetails(
      elementId = 79,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 7,
      group = 8,
      yearDiscovered = "1984",
      standardState = R.string.standard_state_solid,
      description = R.string.hassio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d⁶",
      atomicMass = "269",
      electronegativity = "?",
      atomicRadius = "134",
      ionizationEnergy = "733.3",
      electronAffinity = "?",
      oxidationStates = "+8, +6, +5, +4, +3, +2",
      density = "41000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val meitnerioDetails = ChemicalElementDetails(
      elementId = 80,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 9,
      yearDiscovered = "1984",
      standardState = R.string.standard_state_solid,
      description = R.string.meitnerio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d⁷",
      atomicMass = "278",
      electronegativity = "?",
      atomicRadius = "122",
      ionizationEnergy = "800.8",
      electronAffinity = "?",
      oxidationStates = "+9, +8, +6, +4, +3, +1",
      density = "37400",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val darmstadtioDetails = ChemicalElementDetails(
      elementId = 81,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 10,
      yearDiscovered = "1994",
      standardState = R.string.standard_state_solid,
      description = R.string.darmstadtio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d⁸",
      atomicMass = "281",
      electronegativity = "?",
      atomicRadius = "128",
      ionizationEnergy = "955.2",
      electronAffinity = "?",
      oxidationStates = "+8, +6, +4, +2, 0",
      density = "34800",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val roentgenioDetails = ChemicalElementDetails(
      elementId = 82,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 11,
      yearDiscovered = "1994",
      standardState = R.string.standard_state_solid,
      description = R.string.roentgenio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d⁹",
      atomicMass = "281",
      electronegativity = "?",
      atomicRadius = "121",
      ionizationEnergy = "1022.7",
      electronAffinity = "?",
      oxidationStates = "+5, +3, ±1",
      density = "28700",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val copernicioDetails = ChemicalElementDetails(
      elementId = 83,
      R.drawable.sem_foto,
      series = R.string.series_transition_metal,
      period = 7,
      group = 12,
      yearDiscovered = "1996",
      standardState = R.string.standard_state_solid,
      description = R.string.copernicio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰",
      atomicMass = "285",
      electronegativity = "?",
      atomicRadius = "122",
      ionizationEnergy = "1154.9",
      electronAffinity = "?",
      oxidationStates = "+4, +2, 0",
      density = "23700",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val nihonioDetails = ChemicalElementDetails(
      elementId = 84,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 13,
      yearDiscovered = "2004",
      standardState = R.string.standard_state_solid,
      description = R.string.nihonio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰ 7p¹",
      atomicMass = "286",
      electronegativity = "?",
      atomicRadius = "136",
      ionizationEnergy = "704.9",
      electronAffinity = "?",
      oxidationStates = "+5, +3, +2, +1",
      density = "18000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val flerovioDetails = ChemicalElementDetails(
      elementId = 85,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 14,
      yearDiscovered = "1999",
      standardState = R.string.standard_state_solid,
      description = R.string.flerovio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰ 7p²",
      atomicMass = "289",
      electronegativity = "?",
      atomicRadius = "143",
      ionizationEnergy = "823.9",
      electronAffinity = "?",
      oxidationStates = "+4, +2",
      density = "22000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val moscovioDetails = ChemicalElementDetails(
      elementId = 86,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 15,
      yearDiscovered = "2004",
      standardState = R.string.standard_state_solid,
      description = R.string.moscovio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰ 7p³",
      atomicMass = "288",
      electronegativity = "?",
      atomicRadius = "162",
      ionizationEnergy = "538.4",
      electronAffinity = "?",
      oxidationStates = "+3, +1",
      density = "11000",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val livermorioDetails = ChemicalElementDetails(
      elementId = 87,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 16,
      yearDiscovered = "1999",
      standardState = R.string.standard_state_solid,
      description = R.string.livermorio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰ 7p⁴",
      atomicMass = "293",
      electronegativity = "?",
      atomicRadius = "175",
      ionizationEnergy = "723.6",
      electronAffinity = "?",
      oxidationStates = "+4, +2",
      density = "12900",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val tenessoDetails = ChemicalElementDetails(
      elementId = 88,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 17,
      yearDiscovered = "2010",
      standardState = R.string.standard_state_solid,
      description = R.string.tenesso_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰ 7p⁵",
      atomicMass = "294",
      electronegativity = "?",
      atomicRadius = "?",
      ionizationEnergy = "?",
      electronAffinity = "?",
      oxidationStates = "?",
      density = "?",
      meltingPoint = "?",
      boilingPoint = "?"
   )

   val oganessonDetails = ChemicalElementDetails(
      elementId = 89,
      R.drawable.sem_foto,
      series = R.string.series_unknown_chemical_properties,
      period = 7,
      group = 18,
      yearDiscovered = "1999",
      standardState = R.string.standard_state_solid,
      description = R.string.oganesson_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹⁰ 7p⁶",
      atomicMass = "293",
      electronegativity = "?",
      atomicRadius = "230",
      ionizationEnergy = "?",
      electronAffinity = "?",
      oxidationStates = "+4, +2, 0",
      density = "13.65",
      meltingPoint = "?",
      boilingPoint = "350"
   )

   val lantanioDetails = ChemicalElementDetails(
      elementId = 90,
      R.drawable.lantanio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1839",
      standardState = R.string.standard_state_solid,
      description = R.string.lantanio_desc,
      electronicConfiguration = "[Xe] 6s² 5d¹",
      atomicMass = "138.90547(7)",
      electronegativity = "1.1",
      atomicRadius = "169",
      ionizationEnergy = "538.1",
      electronAffinity = "48.0",
      oxidationStates = "+3, +2",
      density = "6146.0",
      meltingPoint = "1191.0",
      boilingPoint = "3737.0"
   )

   val cerioDetails = ChemicalElementDetails(
      elementId = 91,
      R.drawable.cerio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1803",
      standardState = R.string.standard_state_solid,
      description = R.string.cerio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹ 5d¹",
      atomicMass = "140.116(1)",
      electronegativity = "1.12",
      atomicRadius = "185",
      ionizationEnergy = "534.4",
      electronAffinity = "50.0",
      oxidationStates = "+4, +3, +2",
      density = "6689.0",
      meltingPoint = "1071.0",
      boilingPoint = "3699.0"
   )

   val praseodimioDetails = ChemicalElementDetails(
      elementId = 92,
      R.drawable.praseodimio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1885",
      standardState = R.string.standard_state_solid,
      description = R.string.praseodimio_desc,
      electronicConfiguration = "[Xe] 6s² 4f³",
      atomicMass = "140.93765(2)",
      electronegativity = "1.13",
      atomicRadius = "165",
      ionizationEnergy = "527.0",
      electronAffinity = "50.0",
      oxidationStates = "+4, +3, +2",
      density = "6640.0",
      meltingPoint = "1204.0",
      boilingPoint = "3793.0"
   )

   val neodimioDetails = ChemicalElementDetails(
      elementId = 93,
      R.drawable.neodimio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1885",
      standardState = R.string.standard_state_solid,
      description = R.string.neodimio_desc,
      electronicConfiguration = "[Xe] 6s² 4f⁴",
      atomicMass = "144.242(3)",
      electronegativity = "1.14",
      atomicRadius = "185",
      ionizationEnergy = "533.1",
      electronAffinity = "50.0",
      oxidationStates = "+3, +2",
      density = "6800.0",
      meltingPoint = "1294.0",
      boilingPoint = "3347.0"
   )

   val promecioDetails = ChemicalElementDetails(
      elementId = 94,
      R.drawable.sem_foto,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1945",
      standardState = R.string.standard_state_solid,
      description = R.string.promecio_desc,
      electronicConfiguration = "[Xe] 6s² 4f⁵",
      atomicMass = "145",
      electronegativity = "1.13",
      atomicRadius = "199",
      ionizationEnergy = "540.0",
      electronAffinity = "50.0",
      oxidationStates = "+3",
      density = "7264.0",
      meltingPoint = "1315.0",
      boilingPoint = "3273.0"
   )

   val samarioDetails = ChemicalElementDetails(
      elementId = 95,
      R.drawable.samario,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1879",
      standardState = R.string.standard_state_solid,
      description = R.string.samario_desc,
      electronicConfiguration = "[Xe] 6s² 4f⁶",
      atomicMass = "150.36",
      electronegativity = "1.17",
      atomicRadius = "198",
      ionizationEnergy = "544.5",
      electronAffinity = "50.0",
      oxidationStates = "+3, +2",
      density = "7353.0",
      meltingPoint = "1345.0",
      boilingPoint = "2067.0"
   )

   val europioDetails = ChemicalElementDetails(
      elementId = 96,
      R.drawable.europio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1901",
      standardState = R.string.standard_state_solid,
      description = R.string.europio_desc,
      electronicConfiguration = "[Xe] 6s² 4f⁷",
      atomicMass = "151.964",
      electronegativity = "1.2",
      atomicRadius = "198",
      ionizationEnergy = "547.1",
      electronAffinity = "50.0",
      oxidationStates = "+3, +2",
      density = "5264.0",
      meltingPoint = "1099.0",
      boilingPoint = "1802.0"
   )

   val gadolinioDetails = ChemicalElementDetails(
      elementId = 97,
      R.drawable.gadolinio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1880",
      standardState = R.string.standard_state_solid,
      description = R.string.gadolinio_desc,
      electronicConfiguration = "[Xe] 6s² 4f⁷ 5d¹",
      atomicMass = "157.25(3)",
      electronegativity = "1.2",
      atomicRadius = "196",
      ionizationEnergy = "593.4",
      electronAffinity = "50.0",
      oxidationStates = "+3, +2, +1",
      density = "7901.0",
      meltingPoint = "1586.0",
      boilingPoint = "3546.0"
   )

   val terbioDetails = ChemicalElementDetails(
      elementId = 98,
      R.drawable.terbio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1843",
      standardState = R.string.standard_state_solid,
      description = R.string.terbio_desc,
      electronicConfiguration = "[Xe] 6s² 4f⁹",
      atomicMass = "158.92535(2)",
      electronegativity = "1.2",
      atomicRadius = "194",
      ionizationEnergy = "565.8",
      electronAffinity = "50.0",
      oxidationStates = "+4, +3, +2, +1",
      density = "8219.0",
      meltingPoint = "1629.0",
      boilingPoint = "3503.0"
   )

   val disprosioDetails = ChemicalElementDetails(
      elementId = 99,
      R.drawable.disprosio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1886",
      standardState = R.string.standard_state_solid,
      description = R.string.disprosio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹⁰",
      atomicMass = "162.500(1)",
      electronegativity = "1.22",
      atomicRadius = "192",
      ionizationEnergy = "573.0",
      electronAffinity = "50.0",
      oxidationStates = "+3, +2",
      density = "8551.0",
      meltingPoint = "1685.0",
      boilingPoint = "2840.0"
   )

   val holmioDetails = ChemicalElementDetails(
      elementId = 100,
      R.drawable.holmio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1878",
      standardState = R.string.standard_state_solid,
      description = R.string.holmio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹¹",
      atomicMass = "164.93032(2)",
      electronegativity = "1.23",
      atomicRadius = "192",
      ionizationEnergy = "581.0",
      electronAffinity = "50.0",
      oxidationStates = "+3",
      density = "8800.0",
      meltingPoint = "1747.0",
      boilingPoint = "2973.0"
   )

   val erbioDetails = ChemicalElementDetails(
      elementId = 101,
      R.drawable.erbio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1843",
      standardState = R.string.standard_state_solid,
      description = R.string.erbio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹²",
      atomicMass = "167.259",
      electronegativity = "1.24",
      atomicRadius = "189",
      ionizationEnergy = "589.3",
      electronAffinity = "50.0",
      oxidationStates = "+3",
      density = "9066.0",
      meltingPoint = "1802.0",
      boilingPoint = "3141.0"
   )

   val tulioDetails = ChemicalElementDetails(
      elementId = 102,
      R.drawable.tulio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1879",
      standardState = R.string.standard_state_solid,
      description = R.string.tulio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹³",
      atomicMass = "168.93421(2)",
      electronegativity = "1.25",
      atomicRadius = "190",
      ionizationEnergy = "596.7",
      electronAffinity = "50.0",
      oxidationStates = "+4, +3, +2",
      density = "9321.0",
      meltingPoint = "1818.0",
      boilingPoint = "2223.0"
   )

   val iterbioDetails = ChemicalElementDetails(
      elementId = 103,
      R.drawable.iterbio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1878",
      standardState = R.string.standard_state_solid,
      description = R.string.iterbio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹⁴",
      atomicMass = "173.054",
      electronegativity = "1.1",
      atomicRadius = "187",
      ionizationEnergy = "603.4",
      electronAffinity = "50.0",
      oxidationStates = "+3, +2",
      density = "6570.0",
      meltingPoint = "1097.0",
      boilingPoint = "1469.0"
   )

   val lutecioDetails = ChemicalElementDetails(
      elementId = 104,
      R.drawable.lutecio,
      series = R.string.series_lanthanide,
      period = 6,
      group = 3,
      yearDiscovered = "1878",
      standardState = R.string.standard_state_solid,
      description = R.string.lutecio_desc,
      electronicConfiguration = "[Xe] 6s² 4f¹⁴ 5d¹",
      atomicMass = "174.9668(1)",
      electronegativity = "1.27",
      atomicRadius = "160",
      ionizationEnergy = "523.5",
      electronAffinity = "50.0",
      oxidationStates = "+3",
      density = "9841.0",
      meltingPoint = "1936.0",
      boilingPoint = "3675.0"
   )

   val actinioDetails = ChemicalElementDetails(
      elementId = 105,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1899",
      standardState = R.string.standard_state_solid,
      description = R.string.actinio_desc,
      electronicConfiguration = "[Rn] 7s² 6d¹",
      atomicMass = "227.0278",
      electronegativity = "1.1",
      atomicRadius = "215",
      ionizationEnergy = "499.0",
      electronAffinity = "?",
      oxidationStates = "+3",
      density = "10070.0",
      meltingPoint = "1323.0",
      boilingPoint = "3471.0"
   )

   val torioDetails = ChemicalElementDetails(
      elementId = 106,
      R.drawable.torio,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1828",
      standardState = R.string.standard_state_solid,
      description = R.string.torio_desc,
      electronicConfiguration = "[Rn] 7s² 6d²",
      atomicMass = "232.0381",
      electronegativity = "1.3",
      atomicRadius = "206",
      ionizationEnergy = "587.0",
      electronAffinity = "?",
      oxidationStates = "+4, +3, +2",
      density = "11724.0",
      meltingPoint = "2115.0",
      boilingPoint = "5061.0"
   )

   val proctatinioDetails = ChemicalElementDetails(
      elementId = 107,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1913",
      standardState = R.string.standard_state_solid,
      description = R.string.proctatinio_desc,
      electronicConfiguration = "[Rn] 7s² 5f² 6d¹",
      atomicMass = "231.03588",
      electronegativity = "1.5",
      atomicRadius = "200",
      ionizationEnergy = "568.0",
      electronAffinity = "?",
      oxidationStates = "+5, +4, +3, +2",
      density = "15370.0",
      meltingPoint = "1841.0",
      boilingPoint = "4300.0"
   )

   val uranioDetails = ChemicalElementDetails(
      elementId = 108,
      R.drawable.uranio,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1789",
      standardState = R.string.standard_state_solid,
      description = R.string.uranio_desc,
      electronicConfiguration = "[Rn] 7s² 5f⁴",
      atomicMass = "238.02891(3)",
      electronegativity = "1.38",
      atomicRadius = "175",
      ionizationEnergy = "?",
      electronAffinity = "?",
      oxidationStates = "+6, +5, +4, +3",
      density = "19050.0",
      meltingPoint = "1405.3",
      boilingPoint = "4404.0"
   )

   val neptunioDetails = ChemicalElementDetails(
      elementId = 109,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1940",
      standardState = R.string.standard_state_solid,
      description = R.string.neptunio_desc,
      electronicConfiguration = "[Rn] 7s² 5f⁴ 6d¹",
      atomicMass = "237.0482",
      electronegativity = "1.36",
      atomicRadius = "190",
      ionizationEnergy = "604.5",
      electronAffinity = "?",
      oxidationStates = "+7, +6, +5, +4, +3",
      density = "20250.0",
      meltingPoint = "910.0",
      boilingPoint = "4273.0"
   )

   val plutonioDetails = ChemicalElementDetails(
      elementId = 110,
      R.drawable.plutonio,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1934",
      standardState = R.string.standard_state_solid,
      description = R.string.plutonio_desc,
      electronicConfiguration = "[Rn] 7s² 5f⁶",
      atomicMass = "244.0642",
      electronegativity = "1.28",
      atomicRadius = "187",
      ionizationEnergy = "584.7",
      electronAffinity = "?",
      oxidationStates = "+7, +6, +5, +4, +3",
      density = "19816.0",
      meltingPoint = "912.5",
      boilingPoint = "3505.0"
   )

   val americioDetails = ChemicalElementDetails(
      elementId = 111,
      R.drawable.americio,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1944",
      standardState = R.string.standard_state_solid,
      description = R.string.americio_desc,
      electronicConfiguration = "[Rn] 7s² 5f⁷",
      atomicMass = "243",
      electronegativity = "1.3",
      atomicRadius = "180",
      ionizationEnergy = "578.0",
      electronAffinity = "?",
      oxidationStates = "+7, +6, +5, +4, +3, +2",
      density = "12000.0",
      meltingPoint = "1449.0",
      boilingPoint = "2880.0"
   )

   val curioDetails = ChemicalElementDetails(
      elementId = 112,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1944",
      standardState = R.string.standard_state_solid,
      description = R.string.curio_desc,
      electronicConfiguration = "[Rn] 7s² 5f⁷ 6d¹",
      atomicMass = "247",
      electronegativity = "1.3",
      atomicRadius = "169",
      ionizationEnergy = "581.0",
      electronAffinity = "?",
      oxidationStates = "+4, +3",
      density = "13510.0",
      meltingPoint = "1613.0",
      boilingPoint = "3383.0"
   )

   val berquelioDetails = ChemicalElementDetails(
      elementId = 113,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1949",
      standardState = R.string.standard_state_solid,
      description = R.string.berquelio_desc,
      electronicConfiguration = "[Rn] 7s² 5f⁹",
      atomicMass = "247",
      electronegativity = "1.3",
      atomicRadius = "170",
      ionizationEnergy = "601.0",
      electronAffinity = "?",
      oxidationStates = "+4, +3",
      density = "13250.0",
      meltingPoint = "1323.0",
      boilingPoint = "?"
   )

   val californioDetails = ChemicalElementDetails(
      elementId = 114,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1950",
      standardState = R.string.standard_state_solid,
      description = R.string.californio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁰",
      atomicMass = "251",
      electronegativity = "1.3",
      atomicRadius = "?",
      ionizationEnergy = "608.0",
      electronAffinity = "?",
      oxidationStates = "+4, +3, +2",
      density = "15100.0",
      meltingPoint = "1173.0",
      boilingPoint = "1743"
   )

   val einstenioDetails = ChemicalElementDetails(
      elementId = 115,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1952",
      standardState = R.string.standard_state_solid,
      description = R.string.einstenio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹¹",
      atomicMass = "252",
      electronegativity = "1.3",
      atomicRadius = "?",
      ionizationEnergy = "619.0",
      electronAffinity = "?",
      oxidationStates = "+4, +3, +2",
      density = "884.0",
      meltingPoint = "1133.0",
      boilingPoint = "?"
   )

   val fermioDetails = ChemicalElementDetails(
      elementId = 116,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1955",
      standardState = R.string.standard_state_solid,
      description = R.string.fermio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹²",
      atomicMass = "257",
      electronegativity = "1.3",
      atomicRadius = "?",
      ionizationEnergy = "627.0",
      electronAffinity = "?",
      oxidationStates = "+3, +2",
      density = "?",
      meltingPoint = "1800.0",
      boilingPoint = "?"
   )

   val mendelevioDetails = ChemicalElementDetails(
      elementId = 117,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1955",
      standardState = R.string.standard_state_solid,
      description = R.string.mendelevio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹³",
      atomicMass = "258",
      electronegativity = "1.3",
      atomicRadius = "?",
      ionizationEnergy = "635.0",
      electronAffinity = "?",
      oxidationStates = "+3, +2",
      density = "?",
      meltingPoint = "1100.0",
      boilingPoint = "?"
   )

   val nobelioDetails = ChemicalElementDetails(
      elementId = 118,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1958",
      standardState = R.string.standard_state_solid,
      description = R.string.nobelio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴",
      atomicMass = "259",
      electronegativity = "1.3",
      atomicRadius = "?",
      ionizationEnergy = "1254.3",
      electronAffinity = "?",
      oxidationStates = "+3, +2",
      density = "?",
      meltingPoint = "1100.0",
      boilingPoint = "?"
   )

   val laurencioDetails = ChemicalElementDetails(
      elementId = 119,
      R.drawable.sem_foto,
      series = R.string.series_actinide,
      period = 7,
      group = 3,
      yearDiscovered = "1961",
      standardState = R.string.standard_state_solid,
      description = R.string.laurencio_desc,
      electronicConfiguration = "[Rn] 7s² 5f¹⁴ 6d¹",
      atomicMass = "262",
      electronegativity = "?",
      atomicRadius = "?",
      ionizationEnergy = "443.8",
      electronAffinity = "?",
      oxidationStates = "+3",
      density = "?",
      meltingPoint = "?",
      boilingPoint = "?"
   )
}